# Generated by Django 2.0.1 on 2018-01-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180131_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
