# Generated by Django 2.0.1 on 2018-02-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitrepository',
            options={'verbose_name_plural': 'Git repositories'},
        ),
    ]
