# Generated by Django 2.0.1 on 2018-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180227_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='local_path',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
