# Generated by Django 2.0.1 on 2018-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gitrepository_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='cloning_status',
            field=models.IntegerField(choices=[(0, 'Processing is in progress'), (1, 'Processing is succeed'), (2, 'Processing is failed')], default=0),
        ),
    ]
