# Generated by Django 2.0.1 on 2018-01-31 19:55

import dds.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180131_1936'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemuser',
            managers=[
                ('objects', dds.core.models.SystemUserManager()),
            ],
        ),
    ]
