# Generated by Django 2.0.1 on 2018-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180131_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
