# Generated by Django 2.0.1 on 2018-03-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20180227_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepoController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.CharField(choices=[('I', 'Initial'), ('R', 'Run'), ('S', 'Stop'), ('P', 'Pause')], default='I', max_length=1)),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='core.GitRepository')),
            ],
        ),
    ]
