# Generated by Django 2.0.1 on 2018-03-03 19:03

from django.db import migrations, models
import local_spider_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('local_spider_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepocontroller',
            name='project_setup_bash_file',
            field=models.FileField(null=True, upload_to=local_spider_manager.models.get_project_file_path),
        ),
    ]
