# Generated by Django 2.0.1 on 2018-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_spider_manager', '0002_gitrepocontroller_project_setup_bash_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepocontroller',
            name='current_running_process_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
