# Generated by Django 2.0.1 on 2018-04-15 08:14

from django.db import migrations, models
import local_spider_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('local_spider_manager', '0003_gitrepocontroller_current_running_process_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepocontroller',
            name='project_exec_log_file',
            field=models.FileField(default=1, upload_to=local_spider_manager.models.get_project_file_path),
            preserve_default=False,
        ),
    ]
